### ISSUE TITLE
Create index

### ISSUE THREAD

**Issue by chrislovecnm** [danielfireman/esperf#20]
How are you creating the indexes for testing?

**Comment by danielfireman** [comment]
The index based on the [wikipedia dumps](https://dumps.wikimedia.org/enwiki/20170201/).

To load the index, I used I am using: https://github.com/dustin/go-wikiparse/blob/master/tools/esload/esload.go

Does that answer your question? Was this a feature request? Let me know if you have more questions.

**Comment by chrislovecnm** [comment]
That was it. Thanks
