### ISSUE TITLE
HTTP client doesn't send Content-Type header

### ISSUE THREAD

**Issue by slovdahl** [danielfireman/esperf#22]
As of ES 5.3 the Content-Type header should really be set: https://www.elastic.co/blog/strict-content-type-checking-for-elasticsearch-rest-requests. It will be required from 6.0 and onwards.

My ES deprecation log spams the following for every test at the moment:
```
[2017-09-28T14:02:17,197][WARN ][o.e.d.r.RestController   ] Content type detection for rest requests is deprecated. Specify the content type using the [Content-Type] header.
```

**Comment by danielfireman** [comment]
Hi, @slovdahl, 

PR #23 has just been merged and takes care of this issue. Please let us know how it goes.

**Comment by slovdahl** [comment]
Thank you, that was fast!

I did a quick test to verify that the deprecation log isn't spammed any more at least. Thanks! :bowing_man:

**Comment by danielfireman** [comment]
Thanks for testing it. Releasing a new version now.
