### ISSUE TITLE
package  mousetrap can't find

### ISSUE THREAD

**Issue by liaoyanyunde** [danielfireman/esperf#27]
command_win.go:9:2: cannot find package "github.com/inconshreveable/mousetrap"

**Comment by danielfireman** [comment]
Hi @liaoyanyunde !

Could you please provide more information about the environment you're trying to build esperf? What is the version of Go, GOPATH and so on?

Just to make sure: have you taken a look at https://github.com/danielfireman/esperf/blob/master/CONTRIBUTING.md ?

**Comment by danielfireman** [comment]
Could you please try it now?

**Comment by liaoyanyunde** [comment]
sorry，it's my fault.
this error appear when I buid  the .zip package download from you github in liteide.
in the zip package, some import path is github.com/*/*,but in my system and the source code path is not exist.

in the end ,I independently down those cannot find packages，and build success.

**Comment by liaoyanyunde** [comment]
Thank you for answering my question.

by the way ,do you have a more details usermanual? it's too difficult for me to use it.

**Comment by danielfireman** [comment]
The usage can be found [here](https://github.com/danielfireman/esperf#usage).

You actually don't need to compile esperf. There are pre-built binaries [released](https://github.com/danielfireman/esperf/releases). 

As an example, you can load test Elasticsearch for 5 seconds querying with the term Brazil by simply:

```sh
echo '{"query": {"term": {"text": {"value": "Brazil"}}}}' |  ./esperf loadspec gen --arrival_spec=const:5 --duration=5s "http://localhost:9200/wikipediax/_search"
```

I am closing this issue as the main target has been resolved. Feel free to open new issues if you have find more problems or have more questions. Thanks!

**Comment by liaoyanyunde** [comment]
But when I want to load test the performance when  Insert data or index data, how to do?

**Comment by liaoyanyunde** [comment]
you example just for query

**Comment by danielfireman** [comment]
That's right. Unfortunately, esperf does not currently support [Index API](https://www.elastic.co/guide/en/elasticsearch/reference/current/docs-index_.html). 

Are you keen to add this functionality to esperf :smile:  ? If yes, please open another issue and I am happy to drive you through the needed changes and review the PR.

**Comment by liaoyanyunde** [comment]
Thanks!I will open another issue
