### ISSUE TITLE
panic: runtime error: index out of range with loadspec parseslowlog

### ISSUE THREAD

**Issue by kiml42** [danielfireman/esperf#29]
I'm running the command:
`cat logs/elasticsearch_index_search_slowlog.log | ./esperf loadspec parseslowlog > slowlogs.loadspec.json`
./esperf is a simlink for esperf-v0.1.2-windows-4.0-386.exe

This is the response I'm getting 

> panic: runtime
> 
>  error: index out of range
> 
> goroutine 1 [running]:
> github.com/danielfireman/esperf/cmd/loadspec.glob..func2(0x846320, 0x85919c, 0x0, 0x0, 0x0, 0x0)
>         /ext-go/1/src/github.com/danielfireman/esperf/cmd/loadspec/parse_slowlog.go:79 +0xa4b
> github.com/danielfireman/esperf/vendor/github.com/spf13/cobra.(*Command).execute(0x846320, 0x85919c, 0x0, 0x0, 0x846320, 0x85919c)
>         /ext-go/1/src/github.com/danielfireman/esperf/vendor/github.com/spf13/cobra/command.go:644 +0x2e8
> github.com/danielfireman/esperf/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0x845fc0, 0x6caa20, 0x0, 0x0)
>         /ext-go/1/src/github.com/danielfireman/esperf/vendor/github.com/spf13/cobra/command.go:734 +0x28b
> github.com/danielfireman/esperf/vendor/github.com/spf13/cobra.(*Command).Execute(0x845fc0, 0x0, 0x0)
>         /ext-go/1/src/github.com/danielfireman/esperf/vendor/github.com/spf13/cobra/command.go:693 +0x21
> main.main()
>         /ext-go/1/src/github.com/danielfireman/esperf/main.go:11 +0x23

This is the content of my slowlog:

> [2018-11-15 10:57:43,659][WARN ][index.search.slowlog.query] [Colonel] [test][0] took[23.3ms], took_millis[23], types[], stats[], search_type[QUERY_THEN_FETCH], total_shards[5], source[{"query":{"match":{"test":"test"}}}], extra_source[], 
> [2018-11-15 10:57:43,665][WARN ][index.search.slowlog.query] [Colonel] [test][2] took[26.8ms], took_millis[26], types[], stats[], search_type[QUERY_THEN_FETCH], total_shards[5], source[{"query":{"match":{"test":"test"}}}], extra_source[], 
> [2018-11-15 10:57:43,661][WARN ][index.search.slowlog.query] [Colonel] [test][3] took[107.9micros], took_millis[0], types[], stats[], search_type[QUERY_THEN_FETCH], total_shards[5], source[{"query":{"match":{"test":"test"}}}], extra_source[], 
> [2018-11-15 10:57:43,674][WARN ][index.search.slowlog.query] [Colonel] [test][1] took[13.3ms], took_millis[13], types[], stats[], search_type[QUERY_THEN_FETCH], total_shards[5], source[{"query":{"match":{"test":"test"}}}], extra_source[], 
> [2018-11-15 10:57:43,671][WARN ][index.search.slowlog.query] [Colonel] [test][4] took[95.1micros], took_millis[0], types[], stats[], search_type[QUERY_THEN_FETCH], total_shards[5], source[{"query":{"match":{"test":"test"}}}], extra_source[], 
> [2018-11-15 10:57:43,694][WARN ][index.search.slowlog.fetch] [Colonel] [test][1] took[10.5ms], took_millis[10], types[], stats[], search_type[QUERY_THEN_FETCH], total_shards[5], source[{"query":{"match":{"test":"test"}}}], extra_source[], 

I'm running this on Windows 10 Enterprise version 1803 using GitBash v2.19.1.

**Comment by danielfireman** [comment]
What's the Elasticsearch version? It seems that the slowlogs have changed.

**Comment by kiml42** [comment]
It's using Elasticsearch 2.4.1. It looks like the problem may be the presence of types in the slow log.

Thanks for responding so quickly.

**Comment by kiml42** [comment]
The empty type arrays are the problem. If I search a specific type(/{index}/{type}/_search instead of /{index}/_search), I get the type in the type array for each line, and then it works great.

**Comment by danielfireman** [comment]
I used one your log lines in the unit test added. New released pushed. It should be good to go. Could you please try it out?

**Comment by kiml42** [comment]
That's marvellous, it works great now.
I'm really impressed by how quickly you got this fixed, thank you very much.
